name: Deploy Apigateway service

on:
  workflow_call:
    inputs:
      path-to-root:
        required: true
        type: string
      apply-config:
        required: false
        type: boolean
        default: false
      apply-service-tag:
        required: true
        type: string
jobs:
  apply-k8s-manifests:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ${{ inputs.path-to-root }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: apply-config
        if: inputs.apply-config
        run: kubectl apply -f stage/services/apigateway/config.yaml
      - name: apply-service
        run: |
          export MESSENGER_APIGATEWAY_IMAGE_TAG=${{ inputs.apply-service-tag }}
          kubectl kustomize stage/services/apigateway | envsubst | kubectl apply -f -